{% set data = load_setup_py_data() %}

package:
  name: regain
  version: {{ data.get('version') }}

source:
  git_rev: {{ environ.get('GIT_DESCRIBE_TAG', '') }}
  git_url: https://github.com/fdtomasi/regain.git

requirements:
  build:
    - python
    - nose
    - setuptools
    # - numpy
    # - scipy
    # - scikit-learn
    # - six

  run:
    - python

test:
  imports:
    - regain

about:
  home: https://github.com/fdtomasi/regain
  license: BSD-3
  license_file: LICENSE
