{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0') | replace('v', '') %}

package:
  name: regain
  version: {{ version }}

source:
  git_rev: {{ environ.get('GIT_DESCRIBE_TAG', '') }}
  git_url: https://github.com/fdtomasi/regain.git

requirements:
  build:
    - python
    - pip
    - setuptools >=64

  run:
    - python

test:
  imports:
    - regain

about:
  home: https://github.com/fdtomasi/regain
  license: BSD-3
  license_file: LICENSE
